@startuml
hide footbox
skinparam sequenceReferenceBackgroundColor #

participant "cp:CommandParser" as cp
participant ":Manager" as m

cp -> cp ++ #yellow : addProduct(info)

group sd Manipulating the information
    cp -> cp ++ #green : splitInfo(info)
    return components

    cp -> cp : extract attributes (from components)

    cp -> m ++ : Manager.updateProduct(attributes)

    return
end

return

@enduml
